### ISSUE TITLE
Can't run phyluce_dupe_contig_parser.py script

### ISSUE THREAD

**Issue by WJaratlerdsiri-Lab** [MikeWLloyd/proc-multi-probe-hit#1] opened 2018-12-04 00:31 UTC
Hello,

I like to extract contigs removed for 'hitting multiple probes'. I downloaded the script from https://github.com/MikeWLloyd/proc-multi-probe-hit. 

I ran with the command.

source activate phyluce

python proc-multi-probe-hit/phyluce_dupe_contig_parser.py --output exon_contig8g_fix_multi_probe --contigs exon_contig8g_set2 --dupes exon_contig8g_set2-exonprobe.KEEP_DUPLICATES \
    --fasta exon_contig8g_exonprobe-taxa-incomplete.fasta --conf exon_contig8g_exonprobe-taxa-incomplete.conf \
    --incomplete exon_contig8g_exonprobe-taxa-incomplete.incomplete

Here is the error:

Traceback (most recent call last):
  File "proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 242, in <module>
    main(args)
  File "proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 195, in main
    (added_loci, a) = generateconseq()
  File "proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 170, in generateconseq
    align = AlignIO.read(outfile, "fasta")
  File "/home/vhay1234/anaconda2/envs/phyluce/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 427, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle

I saw "amended_incomplete_matrix.fasta" in my output directory. I went to "exon_contig8g_fix_multi_probe/alignments/" directory and saw an empty fasta file (0 byte in size) with the name format like [contig_name]_[probe_name].fasta.

Could you please suggest me how to fix this? I am appreciated of your time.

Many thanks,
James

**Comment by MikeWLloyd** [comment] 2018-12-04 02:08
Hi James, 

I am not 100% sure how to fix the issue without some additional information, but that error means that the fasta file the script is trying to write, can't be written because it would be empty. 

I suspect that MAFFT is not running/returning properly. Are you sure that you have MAFFT command line installed? I didn't test this script throughly, and only ran it on a linux box. So it could be related to that. 

I would suggest adding a few print statements into the script which should help debug the issue, or at least would give us more information. 

For example can you modify the current script from: 

```
...
        if multi_probe and (values[0] != '') and not re.search("probes hitting multiple contigs", values[0]):
            #values[0] = locus

            added_loci.append(values[0])
            a[taxon].append(values[0])
            #build list of 'new' loci, and associate those loci with correct taxon. 
            #these are used for re-building the .conf and .incomplete files downstream. 

            contigs = set(values[1].split(", "))
            records = (r for r in SeqIO.parse(contig_file, "fasta") if r.id in contigs)
            count = SeqIO.write(records, "temp.file", "fasta")
            mafft_cline = MafftCommandline(input="temp.file")
            stdout, stderr = mafft_cline()
            outfile = args.output + "/alignments/" + taxon + "_" + values[0] + ".fasta"
            with open(outfile, "w") as handle:
                handle.write(stdout)
            #Find the contigs we are interested in and write them into a temporary file, run a mafft alignment on that, and write mafft output to an outfile. 

            align = AlignIO.read(outfile, "fasta")
```

to a script that includes a few print checks: 

```
...
        if multi_probe and (values[0] != '') and not re.search("probes hitting multiple contigs", values[0]):
            #values[0] = locus

            added_loci.append(values[0])
            a[taxon].append(values[0])
            #build list of 'new' loci, and associate those loci with correct taxon. 
            #these are used for re-building the .conf and .incomplete files downstream. 

            contigs = set(values[1].split(", "))
            records = (r for r in SeqIO.parse(contig_file, "fasta") if r.id in contigs)
            count = SeqIO.write(records, "temp.file", "fasta")
            
            mafft_cline = MafftCommandline(input="temp.file")
            #lets see if this prints anything.
            print(mafft_cline)

            stdout, stderr = mafft_cline()
            #lets also check what is in these variables
            print(stdout)
            print(stderr)

            outfile = args.output + "/alignments/" + taxon + "_" + values[0] + ".fasta"
            with open(outfile, "w") as handle:
                handle.write(stdout)
            #Find the contigs we are interested in and write them into a temporary file, run a mafft alignment on that, and write mafft output to an outfile. 

            align = AlignIO.read(outfile, "fasta")
...
```
and run the script again? If you have never written python before, make sure that the print statements have the same number of spaces as the line they occur in. If you can't get the a modified script to run, let me know and I can find try to find time in the next week to make a debugging version. 

e.g.,
```
   line1_3_spaces
   same_line_3_spaces
won't_run_properly_in_this_syntax_with_no_spaces
```

When you run with the added print statements, that might help track down what is going on. 

Sorry, that I can't be more helpful than that.

**Comment by WJaratlerdsiri-Lab** [comment] 2018-12-04 02:56
Thanks Mike,

I managed to make it run and got this:

Working on G0_FD00824587
mafft temp.file


nseq =  0
distance =  ktuples
iterate =  0
cycle =  2
nthread = 0
At least 2 sequences should be input!
Only 0 sequence found.

Traceback (most recent call last):
  File "/scratch/RDS-SMS-PCaGenomes-RW/weejar/phyluce/proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 269, in <module>
    main(args)
  File "/scratch/RDS-SMS-PCaGenomes-RW/weejar/phyluce/proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 222, in main
    (added_loci, a) = generateconseq()
  File "/scratch/RDS-SMS-PCaGenomes-RW/weejar/phyluce/proc-multi-probe-hit/phyluce_dupe_contig_parser.mod.py", line 177, in generateconseq
    align = AlignIO.read(outfile, "fasta")
  File "/home/vhay1234/anaconda2/envs/phyluce/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 427, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle

Do you want to test my input data? I can forward to you now. Few lines of my input are as follows:

less exon_contig8g_exonprobe-taxa-incomplete.fasta
>ex-155489_G0_FD00824587 |ex-155489
ACACACTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCAGCAAGACTGGGAC
AGAGAAAGCTAATGATTGCCAGACAATGAGAAGGGAGATATGAGACTTGGAGGATGTTCA
AAGGAACGCCACAATGAGAGTTAAAAGGTTGGAAAATATAGTGCTCTAGAATCTTATCAC
AGTTGATTACTTGTCCTTCTTCCTATTCAGTCACTCTGTCATCCACCCACCCATTCTCAC
TCAGTCACCACCTTCTCCCAGTCATTTATCTACTCACCCACTTGACACCCACTACTGTCT

less exon_contig8g_set2-exonprobe.KEEP_DUPLICATES
[Altai12_Nea - contigs hitting multiple probes]
NODE_12:ex-156104, ex-156772, ex-156776, ex-156506, ex-156517, ex-156515, ex-156778, ex-157301, ex-156511, ex-157187, ex-157303, ex-156780, ex-157773

[Altai13_Nea - contigs hitting multiple probes]
NODE_13:ex-156513, ex-156355, ex-156512, ex-156357, ex-157773

less exon_contig8g_exonprobe-taxa-incomplete.incomplete
[Altai10_Nea]
ex-154297
ex-154300
ex-154301
ex-154302
ex-154314
ex-154322

less exon_contig8g_exonprobe-taxa-incomplete.conf 
[Organisms]
Altai10_Nea
Altai11_Nea
Altai12_Nea
Altai13_Nea
Altai14_Nea
Altai15_Nea
Altai16_Nea
Altai17_Nea
Altai18_Nea
Altai19_Nea
Altai1_Nea
Altai20_Nea
Altai21_Nea
Altai22_Nea
Altai23_Nea
Altai24_Nea
Altai2_Nea
Altai3_Nea
Altai4_Nea
Altai5_Nea
Altai6_Nea
Altai7_Nea
Altai8_Nea
Altai9_Nea
G0_FD00824587
G1_FD00824587

Thank you for your promising hand. In my case, I really like to run your method as my contig size is very large (N50=90000bp) and it inevitably mapped to a lot of exon probes.

Thanks,
James

**Comment by MikeWLloyd** [comment] 2018-12-04 13:16
Yes, it seems that the script is not pulling out the proper data. I didn't test it for exon capture, just for UCE data. Could be something different in the naming conventions is causing problems. 

If you forward your data, I can try to see what the problem is. No promises as to when I can do that. 

Can you put your data into dropbox, or similar? and provide a link to where I can download the data?

**Comment by WJaratlerdsiri-Lab** [comment] 2018-12-04 22:38
Thanks,

Here is my data & contigs of the sample causing the error (G0_FD00824587):
https://drive.google.com/open?id=1gVRlAEyMi-z_jdIBtjDNFGoWlcMofMvQ

Cheers,
James

**Comment by MikeWLloyd** [comment] 2018-12-05 14:33
The matching line was not catching the assembly headers in the assembly contig file. 

For your data, please modify line 161 of the original script from:
```
records = (r for r in SeqIO.parse(contig_file, "fasta") if r.id in contigs)
```
to: 
```
records = (r for r in SeqIO.parse(contig_file, "fasta") if (r.id.split('_')[0]+"_"+r.id.split('_')[1]) in contigs)
```

I am going to close this, but when you run with the correction, let me know if the problem still occurs.

**Closed as completed by MikeWLloyd** 2018-12-05 14:33 UTC
